export {
  type InterviewState,
  type EntityDraft,
  type CommandDraft,
  QUESTION_TEMPLATES,
  InterviewStateMachine,
} from "./interview-state-machine"

import { InterviewStateMachine } from "./interview-state-machine"

export class InterviewEngine extends InterviewStateMachine {
  getSummary (): string {
    const state = this.getState()
    let summary = `# System Specification: ${state.domain || "Untitled"}\n\n`
    summary += `## Entities (${state.entities.length})\n\n`

    for (const e of state.entities) {
      summary += `### ${e.name}\n`
      summary += `- **Initial State**: ${e.initialState || "N/A"}\n`
      summary += `- **States**: ${e.states.join(", ") || "None defined"}\n`
      summary += `- **Attributes**:\n`
      for (const a of e.attrs) {
        summary += `  - ${a.name}: ${a.type}${a.optional ? " (optional)" : ""}\n`
      }
      if (e.attrs.length === 0) summary += "  - None defined\n"
      summary += "- **Commands**:\n"
      for (const c of e.commands) {
        summary += `  - ${c.name}`
        if (c.fromState && c.toState) summary += ` (${c.fromState} → ${c.toState})`
        summary += "\n"
      }
      if (e.commands.length === 0) summary += "  - None defined\n"
      summary += "\n"
    }

    summary += "---\n"
    summary += `Deployable: ${state.blockingIssues.length === 0 ? "yes" : "no"}\n`
    if (state.blockingIssues.length > 0) {
      summary += "Blocking issues:\n"
      for (const issue of state.blockingIssues) {
        summary += `- ${issue}\n`
      }
    }
    summary += "\n_Generated by CICSC Assistant_"
    return summary
  }

  getStructuredSpec (): { spec: object; deployable: boolean; blocking_issues: string[] } {
    const state = this.getState()
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { TranslationEngine } = require("./translate")
    const translator = new TranslationEngine()
    const spec = translator.translateToSpecJson(state)
    return {
      spec,
      deployable: state.blockingIssues.length === 0,
      blocking_issues: [...state.blockingIssues],
    }
  }
}
