import type { InterviewState } from "./interview-state-machine"
import { isDeployable } from "./blocking-policy"
import { TranslationEngine } from "./translate"

export function renderInterviewSummary (state: InterviewState): string {
  let summary = `# System Specification: ${state.domain || "Untitled"}\n\n`
  summary += `## Entities (${state.entities.length})\n\n`

  for (const e of state.entities) {
    summary += `### ${e.name}\n`
    summary += `- **Initial State**: ${e.initialState || "N/A"}\n`
    summary += `- **States**: ${e.states.join(", ") || "None defined"}\n`
    summary += `- **Attributes**:\n`
    for (const a of e.attrs) {
      summary += `  - ${a.name}: ${a.type}${a.optional ? " (optional)" : ""}\n`
    }
    if (e.attrs.length === 0) summary += "  - None defined\n"
    summary += "- **Commands**:\n"
    for (const c of e.commands) {
      summary += `  - ${c.name}`
      if (c.fromState && c.toState) summary += ` (${c.fromState} → ${c.toState})`
      summary += "\n"
    }
    if (e.commands.length === 0) summary += "  - None defined\n"
    summary += "\n"
  }

  summary += "---\n"
  summary += `Deployable: ${isDeployable(state.blockingIssues) ? "yes" : "no"}\n`
  if (state.blockingIssues.length > 0) {
    summary += "Blocking issues:\n"
    for (const issue of state.blockingIssues) {
      summary += `- [${issue.severity}] ${issue.code} at ${issue.path}: ${issue.message}\n`
    }
  }
  summary += "\n_Generated by CICSC Assistant_"
  return summary
}

export function exportInterviewStructuredSpec (state: InterviewState): {
  spec: object
  deployable: boolean
  blocking_issues: Array<{ code: string; path: string; severity: string; message: string }>
} {
  const translator = new TranslationEngine()
  const spec = translator.toCanonicalSpecJson(state)
  return {
    spec,
    deployable: isDeployable(state.blockingIssues),
    blocking_issues: [...state.blockingIssues],
  }
}
