#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

./control-plane/scripts/export_execution_status.py control-plane/execution/execution-ledger.yaml > control-plane/views/execution-status.generated.json
# Compatibility alias retained during transition window.
cp control-plane/views/execution-status.generated.json control-plane/views/roadmap-status.generated.json
./control-plane/scripts/generate_roadmap_compat.py > /dev/null

python3 - <<'PY'
from pathlib import Path
import json
import yaml

root = Path('.')
obj = yaml.safe_load((root / 'control-plane/objectives/objective-model.yaml').read_text(encoding='utf-8'))
cap = yaml.safe_load((root / 'control-plane/capabilities/capability-model.yaml').read_text(encoding='utf-8'))
exe = yaml.safe_load((root / 'control-plane/execution/execution-ledger.yaml').read_text(encoding='utf-8'))
gate = yaml.safe_load((root / 'control-plane/gates/gate-model.yaml').read_text(encoding='utf-8'))
status = json.loads((root / 'control-plane/views/execution-status.generated.json').read_text(encoding='utf-8'))

phases = exe.get('phases', [])
obj_count = len(obj.get('objectives', []))
cap_count = len(cap.get('capabilities', []))
gate_count = len(gate.get('gates', []))
rows = status.get('rows', [])
status_by_checkbox = {r['checkbox_id']: r['status'] for r in rows}
mode = exe.get('status_source_mode')

phase_status_counts = {}
for p in phases:
    done = 0
    open_ = 0
    for m in p.get('milestones', []):
        for cb in m.get('checkboxes', []):
            s = status_by_checkbox.get(cb['id'])
            if s == 'done':
                done += 1
            elif s == 'open':
                open_ += 1
    phase_status_counts[p['id']] = {'done': done, 'open': open_}

phase_rows = "\n".join([f"| {p['id']} | {p['number']} | {p['title']} | {p['status']} |" for p in phases])
phase_progress_rows = "\n".join(
    [f"| {p['id']} | {phase_status_counts[p['id']]['done']} | {phase_status_counts[p['id']]['open']} |" for p in phases]
)

phase_level = "\n".join([
    "# AUTO-GENERATED FILE. DO NOT EDIT.",
    "# Source: control-plane/execution/execution-ledger.yaml",
    "# Generator: control-plane/scripts/generate_views.sh",
    "",
    "# Phase-Level Roadmap (Generated)",
    "",
    "Canonical status truth is `control-plane/execution/execution-ledger.yaml`.",
    "",
    "## Phase Sequence",
    "",
    "| Phase ID | Number | Title | Status |",
    "|---|---:|---|---|",
    phase_rows,
    "",
    "## Notes",
    "",
    "- This is a non-status planning view generated from control-plane models.",
    "- Do not edit this file directly.",
    "",
    "## Status Projection (From Execution Ledger)",
    "",
    "| Phase ID | Done | Open |",
    "|---|---:|---:|",
    phase_progress_rows,
    "",
])

journey = "\n".join([
    "# AUTO-GENERATED FILE. DO NOT EDIT.",
    "# Source: control-plane/{objectives,capabilities,execution,gates}/*.yaml",
    "# Generator: control-plane/scripts/generate_views.sh",
    "",
    "# Journey Vector (Generated)",
    "",
    "## Model Summary",
    "",
    f"- Objectives: {obj_count}",
    f"- Capabilities: {cap_count}",
    f"- Phases in execution model: {len(phases)}",
    f"- Gate contracts: {gate_count}",
    f"- Status source mode: {mode}",
    "",
    "## Current Sequence",
    "",
    *[f"- Phase {p['number']} ({p['id']}): {p['title']} [{p['status']}]" for p in phases],
    "",
    "## Canonical Rule",
    "",
    "- `control-plane/execution/execution-ledger.yaml` is canonical status truth.",
    "- This file is generated for transparency/navigation only.",
    "",
])

structure_lines = [
    "# AUTO-GENERATED FILE. DO NOT EDIT.",
    "# Source: control-plane/execution/execution-ledger.yaml",
    "# Generator: control-plane/scripts/generate_views.sh",
    "",
    "# Execution Structure (Generated)",
    "",
    "This file captures expected phase/milestone/checkbox structure for non-planned phases.",
    "",
]

for p in phases:
    if p.get('status') == 'planned':
        continue
    structure_lines.append(f"## {p['id']}. Phase {p['number']}: {p['title']}")
    structure_lines.append("")
    for m in p.get('milestones', []):
        structure_lines.append(f"### {m['id']}. {m['title']}")
        structure_lines.append("")
        for cb in m.get('checkboxes', []):
            structure_lines.append(f"- {cb['id']} {cb['title']}")
        structure_lines.append("")

structure = "\n".join(structure_lines)

views = root / 'control-plane' / 'views'
views.mkdir(parents=True, exist_ok=True)
(views / 'phase-level-roadmap.generated.md').write_text(phase_level, encoding='utf-8')
(views / 'journey-vector.generated.md').write_text(journey, encoding='utf-8')
(views / 'roadmap-structure.generated.md').write_text(structure, encoding='utf-8')

# Temporary alias for transition safety.
(views / 'execution-structure.generated.md').write_text(structure, encoding='utf-8')

gate_steps = []
for g in gate.get('gates', []):
    gid = g.get('id')
    for script in g.get('required_scripts', []):
        gate_steps.append({'gate_id': gid, 'script': script})

gate_order = {
    "_generated": True,
    "_source": "control-plane/gates/gate-model.yaml",
    "_generator": "control-plane/scripts/generate_views.sh",
    "version": "cicsc/gate-order-v1",
    "steps": gate_steps,
}
(views / 'gate-order.generated.json').write_text(
    json.dumps(gate_order, indent=2) + "\n", encoding='utf-8'
)

phase_index = {
    "_generated": True,
    "_source": "control-plane/execution/execution-ledger.yaml",
    "_generator": "control-plane/scripts/generate_views.sh",
    "version": "cicsc/phase-index-v1",
    "phases": phases,
}
(views / 'phase-index.generated.json').write_text(
    json.dumps(phase_index, indent=2) + "\n", encoding='utf-8'
)

print('generated control-plane views')
PY
