#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

node <<'NODE'
const fs = require('node:fs')
const path = require('node:path')

const execYaml = fs.readFileSync(path.resolve('control-plane/execution/execution-ledger.yaml'), 'utf8')
const objYaml = fs.readFileSync(path.resolve('control-plane/objectives/objective-model.yaml'), 'utf8')
const capYaml = fs.readFileSync(path.resolve('control-plane/capabilities/capability-model.yaml'), 'utf8')
const gateYaml = fs.readFileSync(path.resolve('control-plane/gates/gate-model.yaml'), 'utf8')

const phases = [...execYaml.matchAll(/^\s*-\s+id:\s+([A-Z]{1,2})\s*\n\s*number:\s*(\d+)\s*\n\s*title:\s*([^\n]+)\n\s*status:\s*(\w+)\s*$/gm)]
  .map((m) => ({ id: m[1], number: Number(m[2]), title: m[3].trim(), status: m[4] }))

const objCount = [...objYaml.matchAll(/^\s*-\s+id:\s+OBJ\d+\s*$/gm)].length
const capCount = [...capYaml.matchAll(/^\s*-\s+id:\s+CAP\d+\s*$/gm)].length
const gateCount = [...gateYaml.matchAll(/^\s*-\s+id:\s+GATE_[A-Z0-9_]+\s*$/gm)].length

const phaseRows = phases.map((p) => `| ${p.id} | ${p.number} | ${p.title} | ${p.status} |`).join('\n')
const phaseLevel = [
  '# AUTO-GENERATED FILE. DO NOT EDIT.',
  '# Source: control-plane/execution/execution-ledger.yaml',
  '# Generator: control-plane/scripts/generate_views.sh',
  '',
  '# Phase-Level Roadmap (Generated)',
  '',
  'Canonical status truth remains `ROADMAP.md` until ledger-source migration is approved.',
  '',
  '## Phase Sequence',
  '',
  '| Phase ID | Number | Title | Status |',
  '|---|---:|---|---|',
  phaseRows,
  '',
  '## Notes',
  '',
  '- This is a non-status planning view generated from control-plane models.',
  '- Do not edit this file directly.',
  ''
].join('\n')

const journey = [
  '# AUTO-GENERATED FILE. DO NOT EDIT.',
  '# Source: control-plane/{objectives,capabilities,execution,gates}/*.yaml',
  '# Generator: control-plane/scripts/generate_views.sh',
  '',
  '# Journey Vector (Generated)',
  '',
  '## Model Summary',
  '',
  `- Objectives: ${objCount}`,
  `- Capabilities: ${capCount}`,
  `- Phases in execution model: ${phases.length}`,
  `- Gate contracts: ${gateCount}`,
  '',
  '## Current Sequence',
  '',
  ...phases.map((p) => `- Phase ${p.number} (${p.id}): ${p.title} [${p.status}]`),
  '',
  '## Canonical Rule',
  '',
  '- `ROADMAP.md` is canonical status truth during bootstrap.',
  '- This file is generated for transparency/navigation only.',
  ''
].join('\n')

fs.mkdirSync(path.resolve('control-plane/views'), { recursive: true })
fs.writeFileSync(path.resolve('control-plane/views/phase-level-roadmap.generated.md'), phaseLevel)
fs.writeFileSync(path.resolve('control-plane/views/journey-vector.generated.md'), journey)

console.log('generated control-plane views')
NODE
