#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

python3 - <<'PY'
from pathlib import Path
import json
import yaml

root = Path('.')
obj = yaml.safe_load((root / 'control-plane/objectives/objective-model.yaml').read_text(encoding='utf-8'))
cap = yaml.safe_load((root / 'control-plane/capabilities/capability-model.yaml').read_text(encoding='utf-8'))
exe = yaml.safe_load((root / 'control-plane/execution/execution-ledger.yaml').read_text(encoding='utf-8'))
gate = yaml.safe_load((root / 'control-plane/gates/gate-model.yaml').read_text(encoding='utf-8'))

phases = exe.get('phases', [])
obj_count = len(obj.get('objectives', []))
cap_count = len(cap.get('capabilities', []))
gate_count = len(gate.get('gates', []))

phase_rows = "\n".join([f"| {p['id']} | {p['number']} | {p['title']} | {p['status']} |" for p in phases])

phase_level = "\n".join([
    "# AUTO-GENERATED FILE. DO NOT EDIT.",
    "# Source: control-plane/execution/execution-ledger.yaml",
    "# Generator: control-plane/scripts/generate_views.sh",
    "",
    "# Phase-Level Roadmap (Generated)",
    "",
    "Canonical status truth remains `ROADMAP.md` until ledger-source migration is approved.",
    "",
    "## Phase Sequence",
    "",
    "| Phase ID | Number | Title | Status |",
    "|---|---:|---|---|",
    phase_rows,
    "",
    "## Notes",
    "",
    "- This is a non-status planning view generated from control-plane models.",
    "- Do not edit this file directly.",
    "",
])

journey = "\n".join([
    "# AUTO-GENERATED FILE. DO NOT EDIT.",
    "# Source: control-plane/{objectives,capabilities,execution,gates}/*.yaml",
    "# Generator: control-plane/scripts/generate_views.sh",
    "",
    "# Journey Vector (Generated)",
    "",
    "## Model Summary",
    "",
    f"- Objectives: {obj_count}",
    f"- Capabilities: {cap_count}",
    f"- Phases in execution model: {len(phases)}",
    f"- Gate contracts: {gate_count}",
    "",
    "## Current Sequence",
    "",
    *[f"- Phase {p['number']} ({p['id']}): {p['title']} [{p['status']}]" for p in phases],
    "",
    "## Canonical Rule",
    "",
    "- `ROADMAP.md` is canonical status truth during bootstrap.",
    "- This file is generated for transparency/navigation only.",
    "",
])

structure_lines = [
    "# AUTO-GENERATED FILE. DO NOT EDIT.",
    "# Source: control-plane/execution/execution-ledger.yaml",
    "# Generator: control-plane/scripts/generate_views.sh",
    "",
    "# Roadmap Structure (Generated)",
    "",
    "This file captures expected phase/milestone/checkbox structure in `ROADMAP.md` for non-planned phases.",
    "",
]

for p in phases:
    if p.get('status') == 'planned':
        continue
    structure_lines.append(f"## {p['id']}. Phase {p['number']}: {p['title']}")
    structure_lines.append("")
    for m in p.get('milestones', []):
        structure_lines.append(f"### {m['id']}. {m['title']}")
        structure_lines.append("")
        for cb in m.get('checkboxes', []):
            structure_lines.append(f"- {cb['id']} {cb['title']}")
        structure_lines.append("")

structure = "\n".join(structure_lines)

views = root / 'control-plane' / 'views'
views.mkdir(parents=True, exist_ok=True)
(views / 'phase-level-roadmap.generated.md').write_text(phase_level, encoding='utf-8')
(views / 'journey-vector.generated.md').write_text(journey, encoding='utf-8')
(views / 'roadmap-structure.generated.md').write_text(structure, encoding='utf-8')

phase_index = {
    "_generated": True,
    "_source": "control-plane/execution/execution-ledger.yaml",
    "_generator": "control-plane/scripts/generate_views.sh",
    "version": "cicsc/phase-index-v1",
    "phases": phases,
}
(views / 'phase-index.generated.json').write_text(
    json.dumps(phase_index, indent=2) + "\n", encoding='utf-8'
)

print('generated control-plane views')
PY
